networks:
    pizza-network:
        driver: bridge

services:
    web:
        container_name: pp_web
        build:
            context: ./
            dockerfile: web.dockerfile
        volumes:
            - ./:/var/www
        ports:
            - '1941:80'
        networks:
            - pizza-network
        links:
            - app

    app:
        container_name: pp_app
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: app.dockerfile
        restart: unless-stopped
        ports:
            - '9012:9000'
            - '${VITE_PORT:-4111}:${VITE_PORT:-4111}'
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        env_file: '.env'
        networks:
            - pizza-network
        links:
            - db

    db:
        image: mariadb:10.4
        container_name: pizza_db
        platform: linux/amd64 #for platform error on Apple M1 chips
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./database:/docker-entrypoint-initdb.d
        ports:
            - '1924:3306'
        networks:
            - pizza-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.2.1
        container_name: pizza_phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            UPLOAD_LIMIT: 300M
        ports:
            - '1931:80'
        networks:
            - pizza-network